# -*- coding: utf-8 -*-
"""mental_health.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/unnikrishnanvarada5-hub/MindBloom/blob/main/mental_health.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import requests
# import random
# from groq import Groq
# 
# # ... (the rest of your styling and chatbot code goes here)
#

!pip install -q streamlit pyngrok groq requests pillow

app_code = """
import streamlit as st
import requests
import random
from groq import Groq

st.set_page_config(
    page_title="MindBloom 🌿",
    page_icon="🌿",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown(\"\"\"
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;1,400&family=DM+Sans:wght@300;400;500&display=swap');
:root{--green:#4caf85;--mint:#a8d5b5;--sage:#d4ede1;--white:#f8fdf9;--charcoal:#2d3a32;--glass:rgba(255,255,255,0.75)}
html,body,[class*=css]{font-family:'DM Sans',sans-serif;background:linear-gradient(135deg,#f0faf4 0%,#e8f5ee 50%,#f5fbf7 100%)!important;color:var(--charcoal)}
section[data-testid=stSidebar]{background:linear-gradient(180deg,#f0faf4,#e8f5ee)!important;border-right:1px solid rgba(76,175,133,.2)}
.bloom-card{background:var(--glass);backdrop-filter:blur(14px);border:1px solid rgba(76,175,133,.25);border-radius:20px;padding:1.4rem 1.6rem;margin-bottom:1rem;box-shadow:0 4px 24px rgba(76,175,133,.1);transition:transform .2s ease,box-shadow .2s ease}
.bloom-card:hover{transform:translateY(-2px);box-shadow:0 8px 32px rgba(76,175,133,.2)}
.bloom-title{font-family:'Playfair Display',serif;font-size:2.6rem;background:linear-gradient(135deg,#3a9e6f,#6dbf94);-webkit-background-clip:text;-webkit-text-fill-color:transparent;text-align:center;margin-bottom:.2rem}
.bloom-subtitle{text-align:center;color:#7a9e88;font-weight:300;font-size:.95rem;margin-bottom:1.5rem}
.chat-user{background:linear-gradient(135deg,#4caf85,#6dbf94);color:#fff;padding:.85rem 1.2rem;border-radius:18px 18px 4px 18px;max-width:80%;margin-left:auto;margin-bottom:.6rem;font-size:.95rem;line-height:1.55;box-shadow:0 3px 12px rgba(76,175,133,.3)}
.chat-bot{background:rgba(255,255,255,0.9);border:1px solid rgba(76,175,133,.3);color:var(--charcoal);padding:.85rem 1.2rem;border-radius:18px 18px 18px 4px;max-width:80%;margin-right:auto;margin-bottom:.6rem;font-size:.95rem;line-height:1.6;box-shadow:0 3px 12px rgba(76,175,133,.1)}
.chat-label{font-size:.72rem;font-weight:500;opacity:.6;margin-bottom:.2rem;text-transform:uppercase;letter-spacing:.05em}
.quote-card{background:linear-gradient(135deg,rgba(76,175,133,.15),rgba(168,213,181,.2));border-left:4px solid #4caf85;border-radius:14px;padding:1.2rem 1.4rem;margin-bottom:.9rem;font-family:'Playfair Display',serif;font-style:italic;font-size:1.05rem;line-height:1.6}
.quote-author{font-family:'DM Sans',sans-serif;font-style:normal;font-size:.8rem;font-weight:500;color:#3a9e6f;margin-top:.5rem;text-align:right}
.gif-card{border-radius:14px;overflow:hidden;background:rgba(255,255,255,0.9);border:1px solid rgba(76,175,133,.2);padding:.8rem;text-align:center;margin-bottom:1rem;box-shadow:0 4px 16px rgba(76,175,133,.1);transition:transform .25s ease}
.gif-card:hover{transform:scale(1.03)}
.gif-card img{border-radius:10px;width:100%;object-fit:cover}
.stButton>button{background:linear-gradient(135deg,#4caf85,#6dbf94)!important;color:#fff!important;border:none!important;border-radius:50px!important;padding:.6rem 1.8rem!important;font-weight:500!important;box-shadow:0 3px 14px rgba(76,175,133,.35)!important}
.stButton>button:hover{transform:translateY(-1px)!important;box-shadow:0 6px 20px rgba(76,175,133,.5)!important}
.stTextArea textarea,.stTextInput input{border:1.5px solid rgba(76,175,133,.4)!important;border-radius:14px!important;background:rgba(255,255,255,.85)!important}
h2,h3{font-family:'Playfair Display',serif!important;color:#2d3a32!important}
#MainMenu,footer{visibility:hidden}
</style>
\"\"\", unsafe_allow_html=True)

QUOTES = [
    ("You don't have to control your thoughts. You just have to stop letting them control you.", "Dan Millman"),
    ("Almost everything will work again if you unplug it for a few minutes, including you.", "Anne Lamott"),
    ("Self-care is not self-indulgence, it is self-preservation.", "Audre Lorde"),
    ("You are allowed to be both a masterpiece and a work in progress simultaneously.", "Sophia Bush"),
    ("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"),
    ("Be gentle with yourself. You are a child of the universe, no less than the trees and the stars.", "Max Ehrmann"),
    ("You don't have to see the whole staircase. Just take the first step.", "Martin Luther King Jr."),
    ("Happiness is not something ready made. It comes from your own actions.", "Dalai Lama"),
    ("It's okay to not be okay — as long as you are not giving up.", "Karen Salmansohn"),
    ("Tough times never last, but tough people do.", "Robert H. Schuller"),
    ("You are braver than you believe, stronger than you seem, and smarter than you think.", "A.A. Milne"),
    ("In the middle of every difficulty lies opportunity.", "Albert Einstein"),
    ("Healing is not linear.", "Anonymous"),
    ("You matter. You are enough. You are loved.", "Anonymous"),
    ("Start where you are. Use what you have. Do what you can.", "Arthur Ashe"),
]

# Funny GIFs from Giphy public endpoints
CUTE_MEDIA = [
    {"url": "https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif",     "label": "🐱 Cat keyboard rage"},
    {"url": "https://media.giphy.com/media/VbnUQpnihPSIgIXuZv/giphy.gif","label": "🐶 Dog vibing"},
    {"url": "https://media.giphy.com/media/MDJ9IbxxvDUQM/giphy.gif",      "label": "🐱 Confused cat"},
    {"url": "https://media.giphy.com/media/ICOgUNjpvO0PC/giphy.gif",      "label": "🐶 Dog head tilt"},
    {"url": "https://media.giphy.com/media/3oriO13KTkzPwTykp2/giphy.gif", "label": "😂 Too relatable"},
    {"url": "https://media.giphy.com/media/5i7umUqAOYYEw/giphy.gif",      "label": "🐱 Cat judging you"},
    {"url": "https://media.giphy.com/media/Nm8ZPAGOwZUQM/giphy.gif",      "label": "🐶 Puppy zoom"},
    {"url": "https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif",      "label": "🐱 Cat drama"},
    {"url": "https://media.giphy.com/media/H4uE6w9G1uK4M/giphy.gif",      "label": "🦆 Duck waddle"},
    {"url": "https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif",  "label": "🐨 Koala chill"},
    {"url": "https://media.giphy.com/media/xT9IgG50Lg7russbD6/giphy.gif", "label": "🐸 Kermit freaking out"},
    {"url": "https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy.gif", "label": "🐣 Baby chick bounce"},
]

SYSTEM_PROMPT = \"\"\"You are MindBloom, a warm, compassionate, and deeply empathetic mental health support companion.
Your personality: Gentle, non-judgmental, always validating. Use soft calming language. Offer practical coping strategies.
Sprinkle in breathing exercises, grounding techniques, or mindfulness tips when appropriate.
Ask thoughtful follow-up questions to understand deeper. If someone seems in crisis, gently encourage professional help
with hotline numbers (iCall India: 9152987821). Use occasional soft emojis (🌿 💚 🌱) but don't overdo it.
Keep responses to 3-5 sentences unless detail is needed. Always end with a supportive closing or gentle question.
You are NOT a replacement for professional therapy.\"\"\"

if "messages"  not in st.session_state: st.session_state.messages  = []
if "groq_key"  not in st.session_state: st.session_state.groq_key  = ""
if "quote_idx" not in st.session_state: st.session_state.quote_idx = random.randint(0, len(QUOTES)-1)
if "media_sel" not in st.session_state: st.session_state.media_sel = random.sample(range(len(CUTE_MEDIA)), 6)

# ── SIDEBAR ──────────────────────────────────────────────────
with st.sidebar:
    st.markdown(\"\"\"
    <div style='text-align:center;padding:1rem 0 0.5rem'>
        <span style='font-size:2.5rem'>🌿</span>
        <div style='font-family:Playfair Display,serif;font-size:1.5rem;
                    background:linear-gradient(135deg,#3a9e6f,#6dbf94);
                    -webkit-background-clip:text;-webkit-text-fill-color:transparent;font-weight:700'>
            MindBloom
        </div>
        <div style='font-size:.78rem;color:#7a9e88;margin-top:.2rem'>Your gentle companion 🌱</div>
    </div>\"\"\", unsafe_allow_html=True)

    st.markdown("---")
    st.markdown("**🔑 Groq API Key**")
    key_in = st.text_input("Key", type="password", value=st.session_state.groq_key,
                           placeholder="gsk_...", label_visibility="collapsed")
    if key_in:
        st.session_state.groq_key = key_in
    st.caption("Free key at [console.groq.com](https://console.groq.com)")

    st.markdown("---")
    st.markdown("**🗺️ Navigate**")
    page = st.radio("", ["💬 Chat with MindBloom", "💡 Motivational Quotes", "😂 Funny GIF Corner"],
                    label_visibility="collapsed")

    st.markdown("---")
    st.markdown("**💭 How are you feeling?**")
    mood = st.select_slider("", options=["😔 Low","😕 Meh","😐 Okay","🙂 Good","😊 Great"],
                            label_visibility="collapsed")
    mood_map = {
        "😔 Low":  ("#a8d5b5", "It's okay to feel low. I'm here with you. 🌿"),
        "😕 Meh":  ("#b5d5c5", "Meh days are valid. Small steps count. 💚"),
        "😐 Okay": ("#c5e0d0", "Okay is perfectly fine. You're doing well. 🌱"),
        "🙂 Good": ("#d0e8da", "That's lovely! Keep nurturing yourself. ✨"),
        "😊 Great":("#e0f2e8", "Wonderful! Spread that warmth around. 🌞"),
    }
    c, m = mood_map[mood]
    st.markdown(f\"\"\"<div style='background:{c}44;border-left:3px solid #4caf85;
        border-radius:10px;padding:.7rem 1rem;font-size:.85rem;color:#2d3a32'>{m}</div>\"\"\",
        unsafe_allow_html=True)

    st.markdown("---")
    st.markdown(\"\"\"<div style='font-size:.75rem;color:#7a9e88;text-align:center;line-height:1.6'>
    🆘 In crisis?<br>
    <b>iCall (India):</b> 9152987821<br>
    <b>Vandrevala:</b> 1860-2662-345<br>
    <b>US Lifeline:</b> 988
    </div>\"\"\", unsafe_allow_html=True)


# ── AI RESPONSE ──────────────────────────────────────────────
def get_ai_response(user_msg):
    if not st.session_state.groq_key:
        return "🔑 Please enter your **Groq API key** in the sidebar. Get a free key at [console.groq.com](https://console.groq.com)."
    try:
        client = Groq(api_key=st.session_state.groq_key)
        msgs = [{"role": "system", "content": SYSTEM_PROMPT}]
        for m in st.session_state.messages[-10:]:
            msgs.append({"role": m["role"], "content": m["content"]})
        msgs.append({"role": "user", "content": user_msg})
        resp = client.chat.completions.create(
            model="llama-3.3-70b-versatile", messages=msgs, max_tokens=600, temperature=0.75
        )
        return resp.choices[0].message.content
    except Exception as e:
        err = str(e)
        if "401" in err or "api_key" in err.lower():
            return "❌ Invalid API key. Please check your Groq API key in the sidebar."
        elif "rate" in err.lower():
            return "⏳ Too many requests. Please wait a moment and try again."
        else:
            return f"⚠️ Something went wrong: {err}"


# ── PAGE: CHAT ───────────────────────────────────────────────
if page == "💬 Chat with MindBloom":
    st.markdown('<div class="bloom-title">MindBloom 🌿</div>', unsafe_allow_html=True)
    st.markdown('<div class="bloom-subtitle">A safe space to talk, heal, and breathe.</div>', unsafe_allow_html=True)

    if not st.session_state.messages:
        st.markdown(\"\"\"<div class="bloom-card" style="text-align:center;padding:2rem">
            <div style="font-size:2rem;margin-bottom:.5rem">🌿</div>
            <div style="font-family:'Playfair Display',serif;font-size:1.2rem;color:#4caf85;margin-bottom:.5rem">
                Hello, I'm MindBloom
            </div>
            <div style="font-size:.9rem;color:#7a9e88;line-height:1.7">
                I'm here to listen without judgment.<br>Share what's on your mind — I'm all ears. 💚
            </div>
        </div>\"\"\", unsafe_allow_html=True)

    for msg in st.session_state.messages:
        if msg["role"] == "user":
            st.markdown(f'<div class="chat-label" style="text-align:right;color:#4caf85">You</div>'
                        f'<div class="chat-user">{msg["content"]}</div>', unsafe_allow_html=True)
        else:
            st.markdown(f'<div class="chat-label" style="color:#4caf85">🌿 MindBloom</div>'
                        f'<div class="chat-bot">{msg["content"]}</div>', unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    if not st.session_state.messages:
        st.markdown("**💭 You could start with...**")
        sugs = ["I've been feeling really anxious lately",
                "I can't sleep and my mind won't stop",
                "I feel lonely and disconnected"]
        c1, c2, c3 = st.columns(3)
        for col, sug, k in zip([c1, c2, c3], sugs, ["s0","s1","s2"]):
            with col:
                if st.button(sug, key=k):
                    st.session_state.messages.append({"role": "user", "content": sug})
                    with st.spinner("🌿 Thinking..."):
                        r = get_ai_response(sug)
                    st.session_state.messages.append({"role": "assistant", "content": r})
                    st.rerun()

    col1, col2 = st.columns([5, 1])
    with col1:
        user_input = st.text_area("", placeholder="Share what's on your mind... 🌱",
                                  key="chat_input", height=90, label_visibility="collapsed")
    with col2:
        st.markdown("<br>", unsafe_allow_html=True)
        send = st.button("Send 💬", use_container_width=True)
        if st.button("Clear 🗑️", use_container_width=True):
            st.session_state.messages = []
            st.rerun()

    if send and user_input.strip():
        st.session_state.messages.append({"role": "user", "content": user_input.strip()})
        with st.spinner("🌿 MindBloom is composing a response..."):
            reply = get_ai_response(user_input.strip())
        st.session_state.messages.append({"role": "assistant", "content": reply})
        st.rerun()


# ── PAGE: QUOTES ─────────────────────────────────────────────
elif page == "💡 Motivational Quotes":
    st.markdown('<div class="bloom-title">Daily Bloom 💡</div>', unsafe_allow_html=True)
    st.markdown('<div class="bloom-subtitle">Words that heal, inspire, and remind you of your strength.</div>', unsafe_allow_html=True)

    q, a = QUOTES[st.session_state.quote_idx]
    st.markdown(f\"\"\"<div class="bloom-card" style="text-align:center;padding:2rem 2.5rem">
        <div style="font-size:2rem;margin-bottom:.8rem">✨</div>
        <div class="quote-card" style="font-size:1.2rem;border:none;background:transparent">"{q}"</div>
        <div class="quote-author" style="font-size:.9rem;text-align:center">— {a}</div>
    </div>\"\"\", unsafe_allow_html=True)

    if st.button("✨ New Quote"):
        st.session_state.quote_idx = random.randint(0, len(QUOTES)-1)
        st.rerun()

    st.markdown("### 🌱 More Wisdom")
    extras = [i for i in range(len(QUOTES)) if i != st.session_state.quote_idx]
    random.shuffle(extras)
    for idx in extras[:6]:
        qt, auth = QUOTES[idx]
        st.markdown(f'<div class="quote-card">"{qt}"<div class="quote-author">— {auth}</div></div>',
                    unsafe_allow_html=True)


# ── PAGE: FUNNY GIF CORNER ───────────────────────────────────
else:
    st.markdown('<div class="bloom-title">😂 Funny GIF Corner</div>', unsafe_allow_html=True)
    st.markdown('<div class="bloom-subtitle">Because laughter is the best medicine — scientifically proven! 🌿</div>',
                unsafe_allow_html=True)

    st.markdown(\"\"\"<div class="bloom-card" style="background:linear-gradient(135deg,rgba(76,175,133,.15),rgba(168,213,181,.2))">
        <div style="font-family:'Playfair Display',serif;font-size:1.1rem;margin-bottom:.6rem">🌬️ Box Breathing — Try it now</div>
        <div style="font-size:.9rem;color:#4a6e56;line-height:1.8">
            <b>Inhale</b> for 4 counts &nbsp;→&nbsp;
            <b>Hold</b> for 4 counts &nbsp;→&nbsp;
            <b>Exhale</b> for 4 counts &nbsp;→&nbsp;
            <b>Hold</b> for 4 counts.<br>
            Repeat 4 times. Your nervous system will thank you. 🌱
        </div>
    </div>\"\"\", unsafe_allow_html=True)

    if st.button("🔄 Shuffle GIFs"):
        st.session_state.media_sel = random.sample(range(len(CUTE_MEDIA)), 6)
        st.rerun()

    st.markdown("### 😂 Today's Laughs")
    cols = st.columns(3)
    for i, idx in enumerate(st.session_state.media_sel):
        item = CUTE_MEDIA[idx]
        with cols[i % 3]:
            st.markdown(f\"\"\"<div class="gif-card">
                <img src="{item['url']}" alt="{item['label']}"/>
                <div style="font-size:.82rem;color:#7a9e88;margin-top:.5rem;font-weight:500">{item['label']}</div>
            </div>\"\"\", unsafe_allow_html=True)

    st.markdown(\"\"\"<div class="bloom-card">
        <div style="font-family:'Playfair Display',serif;font-size:1.1rem;margin-bottom:.6rem">🌱 5-4-3-2-1 Grounding</div>
        <div style="font-size:.9rem;color:#4a6e56;line-height:1.9">
            Notice <b>5 things</b> you can see 👁️<br>
            Notice <b>4 things</b> you can touch 🤲<br>
            Notice <b>3 things</b> you can hear 👂<br>
            Notice <b>2 things</b> you can smell 🌿<br>
            Notice <b>1 thing</b> you can taste 👅<br><br>
            <i>This gently pulls you back to the present moment.</i>
        </div>
    </div>\"\"\", unsafe_allow_html=True)

    affirmations = [
        "I am enough, exactly as I am. 💚",
        "It's okay to rest. Rest is productive. 🌿",
        "I have overcome difficult days before, and I will again. 🌱",
        "My feelings are valid and temporary. ✨",
        "I deserve kindness — especially from myself. 💚",
    ]
    st.markdown("### 🌿 Affirmations for Today")
    for aff in affirmations:
        st.markdown(f\"\"\"<div style='background:linear-gradient(135deg,rgba(76,175,133,.12),rgba(168,213,181,.15));
            border-radius:12px;padding:.75rem 1.1rem;margin-bottom:.6rem;
            font-size:.95rem;color:#2d3a32;border-left:3px solid #4caf85'>{aff}</div>\"\"\",
            unsafe_allow_html=True)
"""

with open("mindbloom_app.py", "w") as f:
    f.write(app_code)

print("✅ App updated with green theme + funny GIFs!")

import subprocess, threading, time
from pyngrok import conf, ngrok, process

# ── PASTE YOUR NGROK AUTHTOKEN HERE ──
NGROK_TOKEN = "3En2Zpwfmw09FDLDUKh7ZgbGzlm_74TsFce3ypqe2dMf1y6iF"   # 👈 your token here

# Kill ALL existing processes
subprocess.run(['pkill', '-f', 'streamlit'], capture_output=True)
subprocess.run(['pkill', '-f', 'ngrok'], capture_output=True)
ngrok.kill()
time.sleep(3)

# Set ngrok authtoken
conf.get_default().auth_token = NGROK_TOKEN

# Start Streamlit in background
def run_streamlit():
    subprocess.run([
        'streamlit', 'run', 'mindbloom_app.py',
        '--server.port', '8501',
        '--server.headless', 'true',
        '--server.enableCORS', 'false',
        '--server.enableXsrfProtection', 'false',
    ])

thread = threading.Thread(target=run_streamlit, daemon=True)
thread.start()
time.sleep(5)

# Create fresh tunnel
public_url = ngrok.connect(8501)

print("=" * 55)
print("🌿  MindBloom is LIVE!")
print("=" * 55)
print(f"\n🔗  Open this URL:\n    {public_url}\n")
print("💡  Enter your FREE Groq API key in the sidebar")
print("    Get one at: https://console.groq.com")
print("=" * 55)